### ISSUE TITLE
Error in HTML documentation for typhon.trees

### ISSUE THREAD

**Issue by JohnMrziglod** [atmtools/typhon#17]
When looking at the daily build documentation for typhon, the documentation extraction for typhon.trees does not seem to work: http://radiativetransfer.org/misc/typhon/doc-trunk/typhon.trees.html

The class IntervalTree is not clickable and one cannot see the docstrings of the class nor its methods.

Does anybody know why?

![screen shot 2017-09-26 at 16 18 15](https://user-images.githubusercontent.com/4180033/30865237-5b8971d8-a2d6-11e7-890c-610adec8d4d5.png)

**Comment by lkluft** [comment]
Hi John,

It seems like Sphinx can't find the class definition. I thougt I had fixed this issue yesterday with https://github.com/atmtools/typhon/commit/44e666bb1edc74663fd7abcd69810d3946d91733 but for some reason the daily build still does not work

**Comment by olemke** [comment]
Whoopsie, that was a bug on the hudson build server. The documentation build updated from github, but never pip-installed the latest version. This was done by the actual test build job, before we moved it to travis. Fixed now.
