### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by lkluft** [atmtools/typhon#18]
Dear all,

our copyright is inconsistent between the PyPi entry (1990-2017) and our documentation (2015-2016). Especially the latter is a bit outdated :wink:

Does anyone really know how this is properly handled?

Cheers,
Lukas

**Comment by olemke** [comment]
There is no copyright year for typhon on PyPi. The 1990-2017 at the bottom of the page is the copyright of PyPi itself.
In our documentation we should just bump the year number.

**Comment by olemke** [comment]
'Bump' actually means incrementing the number, not removing it. But I'm also fine with removing it. I don't think removing it has any negative legal impact.

**Comment by lkluft** [comment]
Oh sorry, I forgot to comment on my commit...

I googled a bit while and removing seems to be the most convenient solution. The copyright is not affected at all.
