### ISSUE TITLE
Allow sub-second temporal placeholders

### ISSUE THREAD

**Issue by gerritholl** [atmtools/typhon#276]
In `FileSet`, the finest temporal placeholder is the `second`.  GOES-16 and GOES-17 filenames contain a sub-second start and end time for each file (see GOES-R Product Definition and User's Guide, Appendix A, Table A-1, page 606, [available here as PDF](https://www.goes-r.gov/products/docs/PUG-L2+-vol5.pdf)):

> `sYYYYDDDHHMMSSs`
> (...)
> SSs = second of minute: 00-60 (... third "s" is tenth of second)

The most general solution would be to allow seconds with any SI-prefix, so that the user could supply `{decisecond}` and `{end_decisecond}`.

**Comment by JohnMrziglod** [comment]
Finally implemented in #307. It also allows centiseconds and microseconds. Nanoseconds are still not supported due to the limitation of pythons timedelta. Hence, I am thinking to switch to pandas or numpy timedeltas in future.
