### ISSUE TITLE
ArrayOfVector not supported in ARTS C API

### ISSUE THREAD

**Issue by lkluft** [atmtools/typhon#28]
## Bug report

Bug report for Freddy.

### Bug summary

The workspace group `ArrayOfVector` is not supported in the API, yet.

### Code for reproduction

```python
from typhon.arts.workspace import Workspace

ws = Workspace()
ws.ArrayOfVectorCreate('aov')
ws.VectorCreate('v')
ws.VectorSetConstant(ws.v, 2, 42.)
ws.Append(ws.aov, ws.v)
ws.aov.value
```

### Actual outcome

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-6-452073056e06> in <module>()
      6 ws.VectorSetConstant(ws.v, 2, 42.)
      7 ws.Append(ws.aov, ws.v)
----> 8 ws.aov.value

~/Documents/typhon/typhon/arts/workspace/variables.py in value(self)
    218                 raise Exception("Variable of type " + self.group + " is empty.")
    219         else:
--> 220             raise Exception("Type of workspace variable is not supported by the interface.")
    221 
    222     def update(self):

Exception: Type of workspace variable is not supported by the interface.
```

### Expected outcome

It would be nice to support `ArrayOfVector` as it is used for `ybatch` results.

## Version information
  * Operating System: osx/Linux
  * Typhon Version: 0.4.0dev
  * Python Version: 3.6

**Comment by simonpf** [comment]
I will get back to this on the weekend. But doing this properly is likely to take me some more time than that.

**Comment by lkluft** [comment]
Thank you, that's perfectly fine! For now, a workaround using XML files does the trick.

It is more about the general utility of this implementation, as `ybatch` is a rather common use case in ARTS :wink:

**Comment by simonpf** [comment]
It might be common, but the interactive interface makes it more or less obsolete.

**Comment by lkluft** [comment]
I totally agree with you! But you should not overestimate the tendency of users to change their habits, especially in our field :wink:

**Comment by simonpf** [comment]
This has been added in [706b9b3](https://github.com/atmtools/typhon/commit/706b9b3217c91add632db0d897c7fec1480b893d). In addition to that you can now use all WSVs of groups that are supported by typhon as function arguments.

For the data transfer I am using temporary XML files. So this is neither fast nor elegant, but the easiest and most general solution I could come up with.
