### ISSUE TITLE
Supergeneric method resolution not working if more than two possible matches of input/output combinations exist

### ISSUE THREAD

**Issue by olemke** [atmtools/typhon#3]
https://github.com/atmtools/typhon/blob/c5eaa79501a917264664365267a63639cc382b8f/typhon/arts/workspace/methods.py#L231-L243

If a supergeneric method has implementations for more than two combinations of input/output, the current implementation fails to find anything but the first two combinations. E.g. the following implementations for Append exist:

1. Append(ArrayOfArrayOfIndex, ArrayOfArrayOfIndex)
2. Append(ArrayOfIndex, ArrayOfIndex)
3. Append(ArrayOfArrayOfIndex, ArrayOfIndex)

Trying to call the 3rd form of Append currently fails with the error that such an overload cannot be found despite it existing.

**Comment by simonpf** [comment]
Fixed in [this commit](https://github.com/atmtools/typhon/commit/391d12f4dc47ae5384cb459217a5481a51275dbd), also added test case [here](https://github.com/atmtools/typhon/commit/2067721c72b96a4ce2994253cc015827ed722ee7#diff-9dd41b330d86ca0497ee6b171346d90cR40).
