### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by simonpf** [atmtools/typhon#370]
Hi, 

We have a study coming up which uses the new QRNN implementation and it would be great to have a release for that.
Are there any plans for a soon-ish 0.9 release?

**Comment by olemke** [comment]
Plan is to release a new typhon version with all the ARTS stuff removed shortly after ARTS 2.4.

**Comment by gerritholl** [comment]
Looks like ARTS 2.4 was released 13 months ago?

**Comment by olemke** [comment]
Resolved by [0.9.0 release](https://github.com/atmtools/typhon/releases/tag/v0.9.0)
