### ISSUE TITLE
Cannot install with conda/mamba on Python 3.9 (or 3.10)

### ISSUE THREAD

**Issue by gerritholl** [atmtools/typhon#396]
### Bug summary

It's currently not possible to install typhon via conda/mamba for Python 3.9 or Python 3.10.

### Code for reproduction

```bash
mamba install -c rttools typhon
```

### Actual outcome

```
Encountered problems while solving:
  - package typhon-0.8.0-py38_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed
```

### Expected outcome

Installation.

## Version information

  * Operating System: openSUSE Leap 15.3
  * Typhon Version: 0.8.0 (attempted install)
  * Python Version: 3.9.7, 3.10.0

My environment is installed from [mambaforge](https://github.com/conda-forge/miniforge#mambaforge) using the conda-forge channel.  I'm aware typhon has previously decided to depend only on packages in Anaconda defaults.  I cannot legally use the Anaconda defaults channel, because the Anaconda terms and conditions prohibit government (or commercial) use.  Fortunately, typhon still works with conda-forge, but I do think typhon might reconsider its Anaconda dependency considering the (new) Anaconda terms and conditions.

**Comment by gerritholl** [comment]
(Typhon couldn't work for Python 3.10 yet even with conda-forge because numba isn't available for Python 3.10 yet, but for Python 3.9 it should be possible even with anaconda defaults)

**Comment by olemke** [comment]
The licensing terms Anaconda chose for their repository are indeed suboptimal. I'll try to release a new typhon version with updated packages that are compatible with miniforge/mambaforge next week. Best cause of action would be of course to get typhon into conda-forge. Unfortunately, I cannot commit any time on that transition currently.

**Comment by olemke** [comment]
@gerritholl, I've put together new packages but would like some additional testing before preparing a typhon release. Can you please try if this package installs properly in your environment? Make sure to remove any previous installation of typhon beforehand:

```
conda install -c olemke typhon-test
```

I've successfully installed it in mambaforge and the current Anaconda release. But a bit more testing couldn't hurt.

**Comment by gerritholl** [comment]
👍  The installation works in my environment.

**Comment by olemke** [comment]
Typhon 0.9.0 with updated conda packages has been released.
