### ISSUE TITLE
Controfiles not found if ARTS_INCLUDE_PATH lacks trailing delimiter.

### ISSUE THREAD

**Issue by lkluft** [atmtools/typhon#4]
https://github.com/atmtools/typhon/blob/c5eaa79501a917264664365267a63639cc382b8f/typhon/arts/workspace/api.py#L56-L57

If the ``ARTS_INCLUDE_PATH`` does not have a trailing delimiter, controlfiles are not found.

I will fix this ;) it is more about testing the issue mechanism

Cheers,
Lukas

**Comment by lkluft** [comment]
Works like a charm! Although it is probably an overkill for such simple issues 😉

**Comment by simonpf** [comment]
how can it be overkill when there's emojis :fire: :rainbow:  :tada:?
