### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by vibinj** [atmtools/typhon#412]
i installed pyarts and arts2.4.
When i tried to run python examples rtcal.ipynb  of arts master i  am getting  error 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_58712/898427790.py in <module>
      4 zenith_angle = 0.0
      5 
----> 6 freq, bt, od = run_arts(species, zenith_angle, height)

~/arts_vib/arts-lectures-master/exercises/04-rtcalc/rtcalc_module.py in run_arts(species, zenith_angle, height, fmin, fmax, fnum, verbosity)
     35     """
     36     ws = pyarts.workspace.Workspace(verbosity=0)
---> 37     ws.water_p_eq_agendaSet()
     38     ws.PlanetSet(option="Earth")
     39     ws.iy_main_agendaSet(option="Emission")

~/arts_vib/arts-2.4.0/build/python/pyarts/workspace/workspace.py in __getattr__(self, name)
    479             i = arts_api.lookup_workspace_variable(name.encode())
    480             if i < 0:
--> 481                 raise AttributeError("No workspace variable " + str(name) + " found.")
    482             vs = arts_api.get_variable(i)
    483             group_id    = vs.group

AttributeError: No workspace variable water_p_eq_agendaSet found

**Comment by olemke** [comment]
This is the typhon repository. If you have a problem with the [arts-lectures](https://github.com/atmtools/arts-lectures), please file an issue in that repository. That being said, please note that the current master of arts-lectures requires ARTS 2.5.8 as described in the README.
