### ISSUE TITLE
Add FAQ about matplotlib error of no X11 connection

### ISSUE THREAD

**Issue by JohnMrziglod** [atmtools/typhon#71]
If I import typhon on a machine where I do not have a X11 connection, I get an error. This results from importing matplotlib which default backend requires a X11 server. The workaround is to import matplotlib before typhon and to set another backend manually. New users or beginners could struggle here, hence it should be covered in a FAQ.

What do you think?

**Comment by gerritholl** [comment]
This is a generic matplotlib issue.  I have in my matplotlibrc I set the backend to agg, when I run interactively I run `ipython --pylab=tk` to get plots.

**Comment by olemke** [comment]
I think it would be good to mention this in the FAQ. A fourth possible fix is to set the environment variable MPLBACKEND: export MPLBACKEND=agg

**Comment by lkluft** [comment]
Thanks for all the feedback 😉 

I will create a FAQ for this issue as it occurred a couple of times within our working group. I will happily include all the different workarounds.

Cheers,
Lukas 🎄
