### ISSUE TITLE
Unresolved symbol set_parameters in latest arts_api

### ISSUE THREAD

**Issue by olemke** [atmtools/typhon#73]
### Bug summary

Trying to `import typhon.arts.workspace` with the latest arts-2-3-900 / typhon-0ff43fa leads to the following error:

```
Loading ARTS API from: /Users/u237002/Hacking/arts-build/gcc/src/libarts_api.so
[snip]
AttributeError: dlsym(0x7fa7d1b07740, set_parameters): symbol not found
```

### Cause of the problem

In arts-2-3-898 the function set_parameters was removed but calls to this function are still present in typhon/arts/workspace/api.py.

**Comment by simonpf** [comment]
Sorry, I could swear I pushed this on Monday. I'll just blame the crappy satellite internet connection I had on the ferry.

Fixed in [adbf73fa](https://github.com/atmtools/typhon/commit/adbf73fa7681ebfe56563cef22aeddd6652747c5).
