### ISSUE TITLE
Restructure tests

### ISSUE THREAD

**Issue by lkluft** [atmtools/typhon#8]
Hi all,

I find myself stumbling across the structure of the tests more and more frequently.

The idea behind the structure as is was to keep implementation and test close to each other in the filetree. In practice, it is often a hassle to determine if there are existing tests and where to find them.

* I suggest to move **all** tests into the top-level `typhon/tests/` directory.

Every subpackage gets an own test module:
```
tests/
|-- test_atmosphere.py
|-- test_geographical.py
|-- test_latex.py
|-- test_spectroscopy.py
-- test_workspace.py
```

The structure within the sub-packages could be emulated by classes (`TestXML`, `TestXMLMatpack`, ...).

What are your opinions? Any arguments to stick to the old system? Or has anyone an even better idea how to structure our tests in general?

Cheers,
Lukas

**Comment by olemke** [comment]
I agree with the new structure. Experience so far has shown that having the tests scattered across all package subdirectories is not helpful.

**Comment by simonpf** [comment]
Yes, I also think that there should be only one subtree for all the tests. But why not mirror the structure
of the source tree?

````
tests/
|-- typhon
    |-- arts
        |-- test_workspace.py
        |-- ...
````
For me that's the simplest mapping from source to test files.

**Comment by lkluft** [comment]
I wanted to limit the number of directories and files for now :wink:

But I guess you are right. Mapping the full project structure in `typhon/tests`  seems to be more intuitive and future-proof.

I will work on the new structure and submit the pull request.
